-- =============================================================================
-- ESQUEMA DO BANCO DE DADOS (SUPABASE / POSTGRESQL)
-- Cole este script no SQL Editor do seu projeto Supabase e clique em RUN.
-- =============================================================================

-- 1. TABELA DE MODELOS DE TONER
CREATE TABLE IF NOT EXISTS modelos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT DEFAULT '',
  estoque_min INTEGER DEFAULT 5,
  cor TEXT DEFAULT '#4f46e5',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE MOVIMENTAÇÕES (ENTRADAS E SAÍDAS)
CREATE TABLE IF NOT EXISTS movimentacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id BIGINT REFERENCES modelos(id) ON DELETE CASCADE NOT NULL,
  tipo TEXT CHECK (tipo IN ('entrada', 'saida')) NOT NULL,
  qty INTEGER NOT NULL CHECK (qty > 0),
  setor TEXT NOT NULL,
  resp TEXT NOT NULL,
  data DATE DEFAULT CURRENT_DATE NOT NULL,
  obs TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ÍNDICES PARA ALTA PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_movimentacoes_modelo_id ON movimentacoes(modelo_id);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_data ON movimentacoes(data DESC);

-- 4. DESABILITAR RLS PARA ACESSO PÚBLICO VIA API ANON (ou configure políticas conforme necessário)
ALTER TABLE modelos DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes DISABLE ROW LEVEL SECURITY;

-- 5. DADOS INICIAIS DE DEMONSTRAÇÃO (OPCIONAL)
INSERT INTO modelos (id, nome, descricao, estoque_min, cor) VALUES
  (1, 'HP CF217A', 'HP LaserJet Pro M102/M130', 5, '#4f46e5'),
  (2, 'HP CE285A', 'HP LaserJet P1102/M1132', 3, '#10b981'),
  (3, 'Samsung MLT-D101', 'Samsung ML-2160/SCX-3405', 4, '#8b5cf6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO movimentacoes (modelo_id, tipo, qty, setor, resp, data, obs) VALUES
  (1, 'entrada', 20, 'Almoxarifado', 'Carlos Silva', '2026-08-01', 'Compra Lote NF-4021'),
  (1, 'saida', 2, 'Recursos Humanos', 'Ana Souza', '2026-08-05', 'Impressora RH 02'),
  (1, 'saida', 3, 'Financeiro', 'Pedro Lima', '2026-08-10', ''),
  (1, 'entrada', 5, 'Almoxarifado', 'Carlos Silva', '2026-08-14', 'Devolução'),
  (1, 'saida', 4, 'TI', 'Lucia Matos', '2026-08-18', 'Laboratório'),
  (2, 'entrada', 10, 'Almoxarifado', 'Carlos Silva', '2026-07-15', ''),
  (2, 'saida', 3, 'Compras', 'Fernanda Costa', '2026-07-20', ''),
  (2, 'saida', 2, 'TI', 'Lucia Matos', '2026-08-02', ''),
  (3, 'entrada', 15, 'Almoxarifado', 'Carlos Silva', '2026-08-01', ''),
  (3, 'saida', 4, 'Operacional', 'Marcos Dias', '2026-08-06', '')
ON CONFLICT DO NOTHING;

-- Atualizar sequências após inserir IDs manuais
SELECT setval(pg_get_serial_sequence('modelos', 'id'), COALESCE(MAX(id), 1)) FROM modelos;
SELECT setval(pg_get_serial_sequence('movimentacoes', 'id'), COALESCE(MAX(id), 1)) FROM movimentacoes;
